version: "2"

run:
  timeout: 5m
  skip-files:
    - ".*_test\\.go$"
    - "tests[\\\\/]"


linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosec
    - gocritic

formatters:
  enable:
    - goimports

issues:
  exclude-rules:
    - path: "tests[\\\\/]"
      linters:
        - errcheck
        - staticcheck
        - unused

output:
  format: colored-line-number