FROM golang:1.23-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git make

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Запускаем тесты
CMD ["sh", "-c", "go test -v -race -coverprofile=coverage.out ./... && go test -v -tags=integration ./tests/integration/..."]