FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache git gcc musl-dev postgresql-client

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=1

# Запускаем тесты
CMD ["go", "test", "-v", "-race", "-coverprofile=coverage.out", "./..."]